#' define path to a cmg extdata folder
#' @export
cmg_extdata_dir = function() paste0(system.file("extdata", package="curatedMetagenomicData"))

#' define path to a template-holding folder subordinate to cmg_tmpdir
#' @export
extdata_dir = function() paste0(cmg_tmpdir(), "/extdata")

#' define path to an "R" folder subordinate to cmg_tmpdir
#' @export
cmg_R_dir = function() paste0(cmg_tmpdir(), "/R")

make_metadata_documentation <- function() {
    template_csv <- read_csv(paste0(cmg_extdata_dir(), "/template.csv"))
    documentation_str <- character(length = 7L)
    documentation_str[1] <-
        "## generated by make_metadata_documentation(): do not edit by hand"
    documentation_str[2] <-
        "\n## see source in data-raw/make_metadata_documentation.R"
    documentation_str[3] <-
        "\n#' Combined metadata of all studies in curatedMetagenomicData\n#'"
    documentation_str[4] <-
        "\n#' The combined sample level metadata of all studies in curatedMetagenomicData.\n#'"
    documentation_str[5] <- documentation_format(template_csv)
    documentation_str[6] <-
        "\n#' @source See dataset specific help functions for source information"
    documentation_str[7] <- "\n\"combined_metadata\"\n"
    cat(documentation_str, file = paste0(cmg_R_dir(), "/combined_metadata.R"))
}
